packages:
  - "packages/*"
  - "apps/*"
onlyBuiltDependencies:
  - esbuild
  - onnxruntime-node
  - protobufjs
  - sharp
allowBuilds:
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
